using DamnORM.Model.Attributes;

namespace DamnORM.unit.tests.Model.POCOs
{
    [DbTable("person")]
    public struct Person
    {
        [DbColumn("id", IsAutogenerated = true)]
        public int ID { get; set; }

        [DbColumn("fname")]
        public string FirstName { get; set; }

        [DbColumn("lname")]
        public string LastName { get; set; }

        [DbColumn("gender")]
        public string Gender { get; set; }

        [DbColumn("age")]
        public int Age { get; set; }
    }
}