using SiteAssets.Common.Model.Attributes;
using System;

namespace DEFAULT_NAMESPACE
{
	[DbTable("person")]
	public class person
	{
		[DbColumn("id", IsAutogenerated = true, CanBeNull = false)]
		public int id { get; set; }

		[DbColumn("fname", MaxLength = 50)]
		public string fname { get; set; }

		[DbColumn("lname", MaxLength = 50)]
		public string lname { get; set; }

		[DbColumn("gender", MaxLength = 1)]
		public string gender { get; set; }

		[DbColumn("age")]
		public int? age { get; set; }

	}
}
